Kp 7172 related material
csc-training/Kielipankki pull request #4
Opened 2023-06-12 07:54 UTC by kaisakui

This PR covers:
- summary of useful links related to corpora and access rights
- courses within the area of data management, programming and HPC.

2023-06-13 07:25 UTC, helhotti requested changes
One super minor thing about the extra parenthesis, but otherwise I think this is quite a comprehensive and helpful list, and all the links seem to work.

2023-06-13 07:25 UTC, helhotti commented on slides/self_study.md
> +    - also available in Finnish as [Ohjelmoinnin perusteet ja jatkokurssi](https://ohjelmointi-23.mooc.fi/))
An extra parenthesis at the end of line 22

2023-06-15 07:24 UTC, aajarven commented on slides/self_study.md
> +    - also available in Finnish as [Ohjelmoinnin perusteet ja jatkokurssi](https://ohjelmointi-23.mooc.fi/))
Whoops, removed!

2023-06-15 07:28 UTC, helhotti approved these changes

2023-06-19 09:46 UTC, merged